DROP PROCEDURE IF EXISTS `insert_once`;

DELIMITER $$
CREATE PROCEDURE insert_once()
Begin

INSERT INTO `configuration_group` (`configuration_group_id`, `configuration_group_key`, `configuration_group_title`, `configuration_group_description`, `sort_order`, `visible`) VALUES ('124', 'INTEGRATION_FACEBOOK_CONF_TITLE', 'Интеграция Facebook', 'Интеграция Facebook', '100', '1');
INSERT INTO `configuration_group` (`configuration_group_id`, `configuration_group_key`, `configuration_group_title`, `configuration_group_description`, `sort_order`, `visible`) VALUES ('125', 'INTEGRATION_GOOGLE_CONF_TITLE', 'Интеграция Google', 'Интеграция Google', '100', '1');
UPDATE `configuration` SET `configuration_group_id`=124 WHERE `configuration_key` in('FACEBOOK_PIXEL_ID','DEFAULT_PIXEL_CURRENCY','FACEBOOK_GOALS_PAGE_VIEW',
'FACEBOOK_GOALS_ADD_TO_CART', 'FACEBOOK_GOALS_CHECKOUT_PROCESS','FACEBOOK_GOALS_SEARCH_RESULTS', 'FACEBOOK_GOALS_COMPLETE_REGISTRATION',
'FACEBOOK_GOALS_VIEW_CONTENT', 'FACEBOOK_GOALS_CONTACT_US_REQUEST', 'FACEBOOK_GOALS_ADD_TO_WISHLIST', 'FACEBOOK_GOALS_ADD_PAYMENT_INFO',
'FACEBOOK_GOALS_SUCCESS_PAGE', 'FACEBOOK_GOALS_CLICK_FAST_BUY','FACEBOOK_GOALS_CLICK_ON_CHAT','FACEBOOK_GOALS_CALLBACK','FACEBOOK_GOALS_FILTER','FACEBOOK_GOALS_SUBSCRIBE','FACEBOOK_GOALS_LOGIN','FACEBOOK_GOALS_ADD_REVIEW','FACEBOOK_GOALS_PHONE_CALL','FACEBOOK_GOALS_CLICK_ON_BUG_REPORT','FACEBOOK_APP_ID','FACEBOOK_APP_SECRET','FACEBOOK_AUTH_STATUS');
UPDATE `configuration` SET `depends_on` = 'facebook_pixel' WHERE `configuration_key` in('FACEBOOK_PIXEL_ID','DEFAULT_PIXEL_CURRENCY','FACEBOOK_GOALS_PAGE_VIEW',
'FACEBOOK_GOALS_ADD_TO_CART', 'FACEBOOK_GOALS_CHECKOUT_PROCESS','FACEBOOK_GOALS_SEARCH_RESULTS', 'FACEBOOK_GOALS_COMPLETE_REGISTRATION',
'FACEBOOK_GOALS_VIEW_CONTENT', 'FACEBOOK_GOALS_CONTACT_US_REQUEST', 'FACEBOOK_GOALS_ADD_TO_WISHLIST', 'FACEBOOK_GOALS_ADD_PAYMENT_INFO',
'FACEBOOK_GOALS_SUCCESS_PAGE', 'FACEBOOK_GOALS_CLICK_FAST_BUY','FACEBOOK_GOALS_CLICK_ON_CHAT','FACEBOOK_GOALS_CALLBACK','FACEBOOK_GOALS_FILTER','FACEBOOK_GOALS_SUBSCRIBE','FACEBOOK_GOALS_LOGIN','FACEBOOK_GOALS_ADD_REVIEW','FACEBOOK_GOALS_PHONE_CALL','FACEBOOK_GOALS_CLICK_ON_BUG_REPORT');
UPDATE `configuration` SET `depends_on` = 'auth' WHERE `configuration_key` in('FACEBOOK_APP_SECRET','FACEBOOK_AUTH_STATUS');
UPDATE `configuration` SET `sort_order`= 39 WHERE `configuration_key` = 'FACEBOOK_AUTH_STATUS';
UPDATE `configuration` SET `sort_order`= 42 WHERE `configuration_key` = 'DEFAULT_PIXEL_CURRENCY';

UPDATE `configuration` SET `configuration_group_id`=125 WHERE `configuration_key` in('GOOGLE_OAUTH_STATUS','GOOGLE_OAUTH_CLIENT_ID','GOOGLE_OAUTH_CLIENT_SECRET','GOOGLE_RECAPTCHA_STATUS','GOOGLE_RECAPTCHA_PUBLIC_KEY','GOOGLE_RECAPTCHA_SECRET_KEY',
'GOOGLE_ANALYTICS_AND_TAGS_MODULE_ENABLED','GOOGLE_TAGS_ID_STATUS','GOOGLE_TAGS_ID','GOOGLE_GOALS_ADD_TO_CART','GOOGLE_GOALS_ON_CHECKOUT','GOOGLE_GOALS_CHECKOUT_PROCESS','GOOGLE_GOALS_CLICK_ON_PHONE','GOOGLE_GOALS_CLICK_FAST_BUY','GOOGLE_GOALS_CLICK_ON_CHAT',
'GOOGLE_GOALS_CLICK_ON_BUG_REPORT','GOOGLE_GOALS_PAGE_VIEW','GOOGLE_GOALS_CALLBACK','GOOGLE_GOALS_FILTER','GOOGLE_GOALS_SUBSCRIBE','GOOGLE_GOALS_LOGIN','GOOGLE_GOALS_ADD_REVIEW','GOOGLE_GOALS_CONTACT_US','GOOGLE_GOALS_CHECKOUT_SUCCESS','GOOGLE_ECOMM_HOME_PAGE',
'GOOGLE_ECOMM_SEARCH_RESULTS','GOOGLE_ECOMM_PRODUCT_DETAIL_PAGE','GOOGLE_ECOMM_CHECKOUT_PAGE','GOOGLE_ECOMM_SUCCESS_PAGE','GOOGLE_SITE_VERIFICATION_KEY');
UPDATE `configuration` SET `depends_on` = 'google_analytics_and_targets' WHERE `configuration_key` in('GOOGLE_ANALYTICS_AND_TAGS_MODULE_ENABLED','GOOGLE_TAGS_ID_STATUS','GOOGLE_TAGS_ID','GOOGLE_GOALS_ADD_TO_CART','GOOGLE_GOALS_ON_CHECKOUT','GOOGLE_GOALS_CHECKOUT_PROCESS','GOOGLE_GOALS_CLICK_ON_PHONE','GOOGLE_GOALS_CLICK_FAST_BUY','GOOGLE_GOALS_CLICK_ON_CHAT',
'GOOGLE_GOALS_CLICK_ON_BUG_REPORT','GOOGLE_GOALS_PAGE_VIEW','GOOGLE_GOALS_CALLBACK','GOOGLE_GOALS_FILTER','GOOGLE_GOALS_SUBSCRIBE','GOOGLE_GOALS_LOGIN','GOOGLE_GOALS_ADD_REVIEW','GOOGLE_GOALS_CONTACT_US','GOOGLE_GOALS_CHECKOUT_SUCCESS','GOOGLE_ECOMM_HOME_PAGE',
'GOOGLE_ECOMM_SEARCH_RESULTS','GOOGLE_ECOMM_PRODUCT_DETAIL_PAGE','GOOGLE_ECOMM_CHECKOUT_PAGE','GOOGLE_ECOMM_SUCCESS_PAGE','GOOGLE_SITE_VERIFICATION_KEY');
UPDATE `configuration` SET `depends_on` = 'auth' WHERE `configuration_key` in('GOOGLE_OAUTH_STATUS','GOOGLE_OAUTH_CLIENT_ID','GOOGLE_OAUTH_CLIENT_SECRET');
UPDATE `configuration` SET `depends_on` = 'recaptcha' WHERE `configuration_key` in('GOOGLE_RECAPTCHA_STATUS','GOOGLE_RECAPTCHA_PUBLIC_KEY','GOOGLE_RECAPTCHA_SECRET_KEY');

END$$
DELIMITER ;
CALL insert_once();

DROP PROCEDURE IF EXISTS `insert_once`;