INSERT INTO `infobox_configuration` (`template_id`, `infobox_file_name`, `infobox_define`, `infobox_display`, `display_in_column`, `location`, `infobox_data`, `callback_data`)
VALUES ('36', 'subscribe.php', 'M_SUBSCRIBE', 0, 2, '15', 'a:3:{s:18:\"subscribe_specials\";a:3:{s:5:\"label\";s:19:\"M_SUBSCRIBE_SPECIAL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:12:\"coupone_mail\";a:3:{s:5:\"label\";s:24:\"M_SUBSCRIBE_COUPONE_MAIL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:7:\"coupone\";a:3:{s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:10:\"getCoupons\";s:5:\"label\";s:19:\"M_SUBSCRIBE_COUPONE\";}}', '');
INSERT INTO `infobox_configuration` (`template_id`, `infobox_file_name`, `infobox_define`, `infobox_display`, `display_in_column`, `location`, `infobox_data`, `callback_data`)
VALUES ('23', 'subscribe.php', 'M_SUBSCRIBE', 0, 2, '15', 'a:3:{s:18:\"subscribe_specials\";a:3:{s:5:\"label\";s:19:\"M_SUBSCRIBE_SPECIAL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:12:\"coupone_mail\";a:3:{s:5:\"label\";s:24:\"M_SUBSCRIBE_COUPONE_MAIL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:7:\"coupone\";a:3:{s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:10:\"getCoupons\";s:5:\"label\";s:19:\"M_SUBSCRIBE_COUPONE\";}}', '');
INSERT INTO `infobox_configuration` (`template_id`, `infobox_file_name`, `infobox_define`, `infobox_display`, `display_in_column`, `location`, `infobox_data`, `callback_data`)
VALUES ('24', 'subscribe.php', 'M_SUBSCRIBE', 0, 5, '15', 'a:3:{s:18:\"subscribe_specials\";a:3:{s:5:\"label\";s:19:\"M_SUBSCRIBE_SPECIAL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:12:\"coupone_mail\";a:3:{s:5:\"label\";s:24:\"M_SUBSCRIBE_COUPONE_MAIL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:7:\"coupone\";a:3:{s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:10:\"getCoupons\";s:5:\"label\";s:19:\"M_SUBSCRIBE_COUPONE\";}}', '');
INSERT INTO `infobox_configuration` (`template_id`, `infobox_file_name`, `infobox_define`, `infobox_display`, `display_in_column`, `location`, `infobox_data`, `callback_data`)
VALUES ('30', 'subscribe.php', 'M_SUBSCRIBE', 0, 5, '15', 'a:3:{s:18:\"subscribe_specials\";a:3:{s:5:\"label\";s:19:\"M_SUBSCRIBE_SPECIAL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:12:\"coupone_mail\";a:3:{s:5:\"label\";s:24:\"M_SUBSCRIBE_COUPONE_MAIL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:7:\"coupone\";a:3:{s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:10:\"getCoupons\";s:5:\"label\";s:19:\"M_SUBSCRIBE_COUPONE\";}}', '');
INSERT INTO `infobox_configuration` (`template_id`, `infobox_file_name`, `infobox_define`, `infobox_display`, `display_in_column`, `location`, `infobox_data`, `callback_data`)
VALUES ('31', 'subscribe.php', 'M_SUBSCRIBE', 0, 5, '15', 'a:3:{s:18:\"subscribe_specials\";a:3:{s:5:\"label\";s:19:\"M_SUBSCRIBE_SPECIAL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:12:\"coupone_mail\";a:3:{s:5:\"label\";s:24:\"M_SUBSCRIBE_COUPONE_MAIL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:7:\"coupone\";a:3:{s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:10:\"getCoupons\";s:5:\"label\";s:19:\"M_SUBSCRIBE_COUPONE\";}}', '');
INSERT INTO `infobox_configuration` (`template_id`, `infobox_file_name`, `infobox_define`, `infobox_display`, `display_in_column`, `location`, `infobox_data`, `callback_data`)
VALUES ('35', 'subscribe.php', 'M_SUBSCRIBE', 0, 5, '15', 'a:3:{s:18:\"subscribe_specials\";a:3:{s:5:\"label\";s:19:\"M_SUBSCRIBE_SPECIAL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:12:\"coupone_mail\";a:3:{s:5:\"label\";s:24:\"M_SUBSCRIBE_COUPONE_MAIL\";s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:11:\"getCheckbox\";}s:7:\"coupone\";a:3:{s:3:\"val\";s:1:\"0\";s:8:\"callable\";s:10:\"getCoupons\";s:5:\"label\";s:19:\"M_SUBSCRIBE_COUPONE\";}}', '');